a1:
	gcc -pthread -w -c adarsh1.c
	gcc -pthread adarsh1.o -o out1
	./out1

a2:
	gcc -pthread -w -c adarsh2.c
	gcc -pthread adarsh2.o -o out2
	./out2

a3:
	gcc -pthread -w -c adarsh3.c
	gcc -pthread adarsh3.o -o out3
	./out3

clean:
	rm -f out1 out2 out3 *.o